### ISSUE TITLE
Implement RC2 from RFC to remove dependency

### ISSUE THREAD

**Issue by paulmey** [Azure/go-pkcs12#11]
As mentioned in #9, we'd like to remove the dependency on ebfe/rc2. That repo does not have a license file, so the status is unclear.

**Comment by nathany** [comment]
> I think we should definitely start a RC2 implementation as soon as we can because the repo we import has no LICENSE and it's an unmaintained fork of an unmaintained repo already. @ahmetalpbalkan

[RFC2268: A Description of the RC2(r) Encryption Algorithm](https://tools.ietf.org/html/rfc2268)

Currently using https://github.com/ebfe/rc2

Here is another implementation, with a license file: https://bitbucket.org/juztin/gocrypto/src/d69e0573b00a?at=default

Not sure about the license on this one: https://code.minty.io/gocrypto/rc2/
> "Package rc2 implements RC2 encryption, as defined in Bruce Schneier's [Applied Cryptography](https://www.schneier.com/books/applied_cryptography/toc.html#chap13)."

**Comment by dgryski** [comment]
I just pushed https://github.com/dgryski/go-rc2 as a preliminary implementation from the RFC.  I didn't look at any of the other implementations.  It can roundtrip some test vectors from the RFC (I didn't add all of them.)

The code needs to be tweaked to implement the cipher.Block interface, but that part is easy and I should be able to get it done in a few space minutes tomorrow (Sunday).

**Comment by nathany** [comment]
Should RC2 be internal to the PKCS12 package or does it make sense to have them as separate packages in x/crypto? @agl

**Comment by dgryski** [comment]
It should be its own package in /x/crypto.

**Comment by dgryski** [comment]
Just pushed https://github.com/dgryski/go-rc2/commit/b3709a2071e1df24564fc378c021df57a055a65d . dgryski/go-rc2 is ~25% faster than ebfe/rc2.

**Comment by ahmetalpbalkan** [comment]
@dgryski awesome. Let's propose your package for stdlib `x/crypto`.
