### ISSUE TITLE
API design: pkcs12.Decode should not make assumptions about the number of certificates and keys

### ISSUE THREAD

**Issue by paulmey** [Azure/go-pkcs12#17]
> Decode extracts a certificate and private key from pfxData.
This function assumes that there is only one certificate and only one private key in the pfxData.

Although this is one of the most-used cases, Decode should not assume that there is only one certificate and one key in the input. To be a proper API for pkcs12, it should probably return a list of decoded/decrypted safebag contents?

**Comment by nathany** [comment]
should -> shouldn't

a list makes sense. b.Type is available.

**Comment by paulmey** [comment]
I'm considering removing `func Decode(pfxData []byte, utf8Password []byte) (privateKey interface{}, certificate *x509.Certificate, err error)` in favor of `func ConvertToPEM(pfxData []byte, utf8Password []byte) (blocks []*pem.Block, err error)`

**Comment by nathany** [comment]
Fine by me. I haven't used Decode yet. :-)

Right now I'm using a wrapper function that I would need to adjust to handle multiple keys/certs:

```go
func decodePKCS(p12, password []byte) (tls.Certificate, error) {
	blocks, err := pkcs12.ConvertToPEM(p12, password)
	if err != nil {
		return tls.Certificate{}, err
	}

	var certPEM, keyPEM []byte
	for _, b := range blocks {
		switch b.Type {
		case "CERTIFICATE":
			certPEM = pem.EncodeToMemory(b)
		case "PRIVATE KEY":
			keyPEM = pem.EncodeToMemory(b)
		default:
			return tls.Certificate{}, fmt.Errorf("Unrecognized block type: %s", b.Type)
		}
	}

	return tls.X509KeyPair(certPEM, keyPEM)
}
```

I'm not sure if it makes sense to have higher-level APIs like this in x/crypto itself, but I'm guessing not.

Aside: one thing I'd like to see is exported constants for "CERTIFICATE" and "PRIVATE KEY".

**Comment by paulmey** [comment]
I wrote that mainly to satisfy the implementation of [`tls.X509KeyPair(certPEMBlock, keyPEMBlock []byte)`](https://golang.org/src/crypto/tls/tls.go?s=5110:5190#L174), which you are using.

Would it make sense to have a method that directly returns an array of keypairs?

**Comment by nathany** [comment]
Nah. I think it's possible to have two certs and one key or strange situations like that. So just the array of PEM stuff seems best to me.

**Comment by paulmey** [comment]
Closing this, since `ConvertToPEM` is available for this purpose.
