### ISSUE TITLE
Why unset password variables?

### ISSUE THREAD

**Issue by GeertJohan** [Azure/go-pkcs12#3]
https://github.com/Azure/go-pkcs12/blob/master/crypto.go#L61
https://github.com/Azure/go-pkcs12/blob/master/pkcs12.go#L77

Why are the password variables unset?
This looks like a useless action to me, the old data isn't removed from memory because they're still being referred to from outside the function. And even if they weren't, it would require GC to totally clean them from memory..

If you want the functions to clear the passwords from memory: use `[]byte` in both cases and add a `for range` setting each byte to `0x00` or something random.

**Comment by ahmetalpbalkan** [comment]
@paulmey agreed. unless we have a language builtin like SecureString, we should be accepting passwords only as []byte. Once they're string, they are interned.

**Comment by paulmey** [comment]
I'm rewriting the bmpstring func to take UTF-8 bytes and convert to BMP string bytes. We can then change strings to []byte and zero them out after use.

**Comment by GeertJohan** [comment]
Sounds good. I'm not too familiar with BMP string bytes, but concerning UTF-8 you might be interested in using runes instead of bytes. https://blog.golang.org/strings has good information about the use of bytes and runes and strings..

**Comment by paulmey** [comment]
Take a look at the PR. The BMP conversion loop didn't change much, I just decode utf8 and re-encode utf16 checking if it's still within UCS2. I did not find an easy way to go from a `string` to a `[]rune`, so I think `[]byte` is the best choice?

**Comment by dgryski** [comment]
Note that just clearing the slices is not a guarantee. The Go cipher types had a Reset() method removed for exactly this reason. http://golang.org/doc/go1#crypto_aes_des

**Comment by ahmetalpbalkan** [comment]
@dgryski valid point. runtime can do all sorts of magic and preserve copies multiple copies of things. Unless the language doesnt have a builtin to support secure strings, they're not secure at all. We can be good citizens and probably still accept []byte or []rune though.

**Comment by paulmey** [comment]
Is there *any* way to get a guarantee?

**Comment by dgryski** [comment]
Using a slice of runes will make the callers do extra work if they're reading the password from a configuration file as a []byte. What will the code for the average case look like now?

**Comment by dgryski** [comment]
@paulmey not at the moment. There are no built in types for this and with a copying collector on the horizon that makes it even harder. It would require quite a bit of compiler and runtime support. Feel free to file an issue, but there likely is one already.

**Comment by paulmey** [comment]
Since `string` can be easily converted to both `[]byte` and `[]rune`, the argument that @dgryski makes for reading from file or other stream makes sense to me. I vote for switching back to []byte... @ahmetalpbalkan @GeertJohan any opinions?

**Comment by GeertJohan** [comment]
As @dgryski  points out, []byte is more commonly used. I suspect that there's not often a need to split the password to individual utf-8 codepoints, so yes it makes sense to switch back to bytes.

**Comment by ahmetalpbalkan** [comment]
[]byte sounds good then unless we do any utf-8 -> utf-16 like conversion

**Comment by paulmey** [comment]
We actually do a utf8->UCS2 conversion, since that's what a BMPstring is. You could say that UCS2 is a subset of utf16, so I'm using the utf16 encoder to find the right representations.

**Comment by paulmey** [comment]
PR updated to []byte

**Comment by dgryski** [comment]
The documentation for Decode and ConvertToPEM should be updated to mention that utf8Password will be cleared.

**Comment by paulmey** [comment]
Good point

**Comment by nathany** [comment]
So in the standard library's PEM decrypt, it is the callers responsibility to zero out the password? (Which still isn't guaranteed anyway as per the removal of `Reset()`.)

**Comment by dgryski** [comment]
@nathany Correct.

**Comment by nathany** [comment]
Even if the pkcs library didn't clear passwords, using a []byte slice is still an improvement on string, as it matches x509.Decode and it *may* not make a copy.

**Comment by paulmey** [comment]
To clear or not to clear, I'm kinda pragmatic here, so I'm fine with either. @ahmetalpbalkan , you seem to always support aligning with std lib patterns? Opinion?

**Comment by nathany** [comment]
If the passwords aren't cleared out by go-pkcs12, perhaps the example in the README could clear out the passwords?
