### ISSUE TITLE
using bytes.Compare in MAC validation leaks timing information 

### ISSUE THREAD

**Issue by dgryski** [Azure/go-pkcs12#6]
The code should use http://golang.org/pkg/crypto/subtle/#ConstantTimeCompare to avoid a timing attack.

**Comment by dgryski** [comment]
The code is already using hmac. Use hmac.Equal instead.

**Comment by paulmey** [comment]
@dgryski Thanks for the catch. Is the PR the right fix?

**Comment by dgryski** [comment]
Looks good to me.
