### ISSUE TITLE
Merge this package to the Go standard library

### ISSUE THREAD

**Issue by rakyll** [Azure/go-pkcs12#9]
PKCS 12 is a wildly popular container format even though the Go standard library doesn't provide a native decoder/encoder. It's not ideal for the standard library packages (and our sub-packages) to have third-party dependencies, hence I can't reuse your implementation. Upstreaming pkcs12 to the Go standard library would be mutually beneficial.

**Comment by ahmetalpbalkan** [comment]
:+1: 

:confetti_ball: :confetti_ball: :confetti_ball: 
:dancer: :dancer: :dancer:

**Comment by dgryski** [comment]
That would also require importing github.com/ebfe/rc2 to /x/crypto.

**Comment by rakyll** [comment]
I would open an issue on the tracker and cc @agl before committing any work.

**Comment by agl** [comment]
This might be reasonable for the crypto subrepo, but I don't feel that it should be in the standard library.

**Comment by nathany** [comment]
If I understand correctly, https://github.com/golang/crypto isn't covered by the same backwards compatibility guarantee as the Go standard library, making it a little more flexible?

**Comment by rakyll** [comment]
Could you (or should I) move the conversation to the [Go issue tracker](https://github.com/golang/go/issues)? The ongoing conversation needs visibility in the wider Go audience.

**Comment by nathany** [comment]
Would it make sense to refine the API a bit more before moving it to golang/crypto or does that matter?

I'm thinking of the error handling discussed in #2 (trivial), and perhaps providing a way to encode PEM into PKCS12.

Perhaps that is exactly the sort of discussion to be had with the wider Go audience, so I agree with opening an issue in https://github.com/golang/go/issues for a crypto/pkcs12 package. @paulmey, what do you think?

**Comment by paulmey** [comment]
@nathany I agree that baking the package here is a good idea, I have no problem with opening an issue at golang to get a wider discussion.

Would it make sense to also start an RC2 implementation from the RFC memo to avoid reliance on ebfe/rc2 ?

Encoding to p12 and multi-cert (exported chains) make sense as additional features.

**Comment by ahmetalpbalkan** [comment]
I think we should definitely start a RC2 implementation as soon as we can because [the repo](https://github.com/ebfe/rc2) we import has no LICENSE and it's an unmaintained fork of an unmaintained repo already.

**Comment by dgryski** [comment]
I have lots of experience implementating crypto algorithms from RFCs or the original papers. Shouldn't be too hard, but I'd need to find some free time.

**Comment by paulmey** [comment]
@nathany @rakyll , does the current API for this package support all of the scenario's that you would like to use it for, or should we add certain features before proposing it for the crypto sub repo?

**Comment by paulmey** [comment]
@dgryski, do you already have an issue open to propose rc2 for addition to the golang/crypto sub repo?

**Comment by dgryski** [comment]
@paulmey I have not opened any issue regarding rc2 inclusion.

**Comment by nathany** [comment]
I'm still trying to get more information about the cert, having only looked at the Type and Headers.

I noticed that x509 parses the extensions, which can contain useful information. For Apple .p12 certs there are extensions to indicate whether the cert is for sandbox or production. It seems like I should be able to determine from tls cert after conversion. 

My question is whether or not their is anything *lost in translation*? Another thing I'd like to determine is if the p12 cert has expired, or find out how to check if it has been revoked.

So far I don't need writing of p12.

Besides tweaking the errors API, I think a few other places could benefit from tweaking. For example, I'd prefer not to compare Type to "PRIVATE KEY", and instead have the package export constants for the available types.

**Comment by rakyll** [comment]
API related discussion doesn't belong to the current issue. Please, open an issue against https://github.com/golang/go/issues to propose an API to ask for feedback. The owners of the crypto package can't see the discussion here.

**Comment by paulmey** [comment]
Let's continue the API discussion at https://github.com/golang/go/issues/10621
